//server routes
module.exports = {
    // Root: "https://t3dweb.herokuapp.com",
    Root: "https://t3d.iran.liara.run",
    // WebSocketRoot: "wss://t3dweb.herokuapp.com/ws",
    WebSocketRoot: "wss://t3d.iran.liara.run/ws",

    wsGamePlayRoute: "gameplay",
    wsGlobalRoute: "global",
    SignUp: "signup",
    SignIn: "signin",
    Users: "users",
    Private: "private",
    Credentials: "credentials",
    MyAvatar: "avatar",
    PasswordChange: "password",
    Friends: "friends",
    Records: "records",
    Administrators: "administrators",
    Games: "games",
    Mine: "mine",
    Leagues: "leagues",
    NewLeague: "new",
    LeaguesList: "list",
    Attend: "attend",
    Chats: "chats",
    Interactions: "interact",
    SingleChat: "single",
    Notices: "notices",
    NoticeManagement: "manage"
};
